rm -rf "DFU\DFUSe\STDFU\Debug"
rmdir /S /Q "Dfu\DFUSe\STDFU\Debug"
rm -rf "DFU\DFUSe\STDFU\Release"
rmdir /S /Q "DFU\DFUSe\STDFU\Release"
rm -rf "DFU\DFUSe\STDFUFiles\Debug"
rmdir /S /Q "DFU\DFUSe\STDFUFiles\Debug"
rm -rf "DFU\DFUSe\STDFUFiles\Release"
rmdir /S /Q "DFU\DFUSe\STDFUFiles\Release"
rm -rf "DFU\DFUSe\STDFUPRT\Debug"
rmdir /S /Q "DFU\DFUSe\STDFUPRT\Debug"
rm -rf "DFU\DFUSe\STDFUPRT\Release"
rmdir /S /Q "DFU\DFUSe\STDFUPRT\Release"
rm -rf "DFU\DFUSe\STTubeDevice\Debug"
rmdir /S /Q "DFU\DFUSe\STTubeDeviceT\Debug"
rm -rf "DFU\DFUSe\STTubeDevice\Release"
rmdir /S /Q "DFU\DFUSe\STTubeDevice\Release"
rm -rf "DFU\NewDFUSe\dfu-util\Debug"
rmdir /S /Q "DFU\NewDFUSe\dfu-util\Debug"
rm -rf "DFU\NewDFUSe\dfu-util\Release"
rmdir /S /Q "DFU\NewDFUSe\dfu-util\Release"
rm -rf "DFU\NewDFUSe\getopt\Debug"
rmdir /S /Q "DFU\NewDFUSe\getopt\Debug"
rm -rf "DFU\NewDFUSe\getopt\Release"
rmdir /S /Q "DFU\NewDFUSe\getopt\Release"
rm -rf "DFU\NewDFUSe\libusb\Debug"
rmdir /S /Q "DFU\NewDFUSe\libusb\Debug"
rm -rf "DFU\NewDFUSe\libusb\Release"
rmdir /S /Q "DFU\NewDFUSe\libusb\Release"
rm -rf "HubSchemes\Debug"
rmdir /S /Q "HubSchemes\Debug"
rm -rf "HubSchemes\Debug"
rmdir /S /Q "HubSchemes\Debug"
rm -rf "HubSchemes\Release"
rmdir /S /Q "HubSchemes\Release"
rm -rf "HydronicPics\Debug"
rmdir /S /Q "HydronicPics\Debug"
rm -rf "HydronicPics\Release"
rmdir /S /Q "HydronicPics\Release"
rm -f -r -v "HydronicPics\HydronicPics.aps"
rm -rf "HydronicPics\LPP_AT\Debug"
rmdir /S /Q "HydronicPics\LPP_AT\Debug"
rm -rf "HydronicPics\LPP_AT\Release"
rmdir /S /Q "HydronicPics\LPP_AT\Release"
rm -f -r -v "HydronicPics\StdAfx.pch.ib_tag"
rm -f -r -v "HydronicPics\StdAfx.pch"
rm -rf "ipch"
rmdir /S /Q "ipch"
rm -rf "Spread\FpLibs\FPTOOLS\DLL32\objud32"
rmdir /S /Q "Spread\FpLibs\FPTOOLS\DLL32\objud32"
rm -rf "Spread\FpLibs\FPTOOLS\DLL32\obju32"
rmdir /S /Q "Spread\FpLibs\FPTOOLS\DLL32\obju32"
rm -rf "Spread\SS\Src\Excel\objud32"
rmdir /S /Q "Spread\SS\Src\Excel\objud32"
rm -rf "Spread\SS\Src\Excel\obju32"
rmdir /S /Q "Spread\SS\Src\Excel\obju32"
rm -rf "Spread\SS\Src\ssw\objud32"
rmdir /S /Q "Spread\SS\Src\ssw\objud32"
rm -rf "Spread\SS\Src\ssw\obju32"
rmdir /S /Q "Spread\SS\Src\ssw\obju32"
attrib +a "TASelect\Debug\*.*" /s
for %%i in ("TASelect\Debug\*.exe" "TASelect\Debug\*.dll") do attrib -a %%i /s
del "TASelect\Debug\*.*" /F /s /q
rmdir /S /Q "TASelect\Debug"
attrib +a "TASelect\Release\*.*" /s
for %%i in ("TASelect\Release\*.exe" "TASelect\Release\*.dll") do attrib -a %%i /s
del "TASelect\Release\*.*" /F /s /q
rmdir /S /Q "TASelect\Release"
rm -f -r -v "TASelect\TASelect.aps"
rm -f -r -v "TASelect\StdAfx.pch.ib_tag"
rm -f -r -v "TASelect\StdAfx.pch"
rm -rf "ZipArchive\Debug STL Unicode"
rmdir /S /Q "ZipArchive\Debug STL Unicode"
rm -rf "ZipArchive\Release STL Unicode"
rmdir /S /Q "ZipArchive\Release STL Unicode"
del "lib\Debug\*.*" /F /s /q
rmdir /S /Q "lib"
del /F /Q "*.sdf"
del /F /Q /AH "*.suo"
del /F /Q /S "Spread\SS\Dll\*.*"
del /F /Q /S "Spread\SS\Lib\*.*"
del /F /Q /S "UnitTests\cppunit\src\cppunit\Debug\*.*"
rmdir /S /Q "UnitTests\cppunit\src\cppunit\Debug"
