/*
$Revision:   1.3  $
*/

/*
 * Dialog defines for libdial
 */

/* global dialog defines */
#define  IDD_OKBUTTON         100
#define  IDD_CANCELBUTTON     101


/*  printer setup dialog */
#define  IDD_PRSETUPSETUP     200
#define  IDD_PRSETUPLIST      201


/* OPEN FILE DIALOGS  */
#define  IDD_FILENAME         300
#define  IDD_FILELIST         301
#define  IDD_DIRLIST          302
#define  IDD_DIR              303

/* page setup dialog */
#define  IDD_HEADER           400
#define  IDD_FOOTER           401
#define  IDD_TOP              402
#define  IDD_LEFT             403
#define  IDD_RIGHT            404
#define  IDD_BOTTOM           405

/* OPEN FILE #2 */
#define  IDD_OPEN             500

/* font dialog */
#define  IDD_FONTLIST         600   
#define  IDD_FACENAME         601
#define  IDD_SIZELIST         602
#define  IDD_SIZEEDIT         603
#define  IDD_BOLD             604
#define  IDD_ITALIC           605
#define  IDD_UNDERLINE        606
#define  IDD_EDIT             607
#define  IDD_STRIKEOUT        608
#define  IDD_PRINTER          609
#define  IDD_TESTTEXT         610

/* Calendar Dialog */
#define IDD_DAYLIST           700
#define IDD_STATIC			  701
