//--------------------------------------------------------------------
//
//  File: ss_rwde.h
//
//  Description: Provides support for Borland's Resource Workshop
//               dialog editor.
//

#define IDD_SS_IDNAME            501
#define IDD_SS_IDVALUE           502
#define IDD_SS_TEXT              503
#define IDD_SS_TABSTOP           504
#define IDD_SS_DISABLED          505
#define IDD_SS_GROUP             506
#define IDD_SS_BORDER            507
#define IDD_SS_ALLOWCELLOVERFLOW 508
#define IDD_SS_ALLOWUSERFORMULAS 509
#define IDD_SS_HIDECOLHEADERS    510
#define IDD_SS_HIDEROWHEADERS    511
#define IDD_SS_LOCKALL           512
#define IDD_SS_NOGRIDLINES       513
#define IDD_SS_NORESIZE          514
#define IDD_SS_NOSELECTBLOCK     515
#define IDD_SS_RESTRICTROWS      516
#define IDD_SS_RESTRICTCOLS      517
#define IDD_SS_SCROLLBAREXTMODE  518
#define IDD_SS_SPREADSHEETSTYLES 519
#define IDD_SS_WINDOWSTYLES      520
