

LONG FP_Action(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
               WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_Font(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
             WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_AllowResize();
LONG FP_AllowSelBlock();
LONG FP_AutoCalc();
LONG FP_BackColor();
LONG FP_Calc_Dept();
LONG FP_CellType1();
LONG FP_ClipValue();
LONG FP_Clip();
LONG FP_Col();
LONG FP_Col2();
LONG FP_ColWidth();
LONG FP_DisplayColHeaders();
LONG FP_DisplayRowHeaders();
LONG FP_EditMode();
LONG FP_ForeColor();
LONG FP_Formula();
LONG FP_GridLines();
LONG FP_LeftCol();
LONG FP_Lock();
LONG FP_MaxCols();
LONG FP_MaxRows();
LONG FP_Protect();
//LONG FP_Redraw();
LONG FP_RestrictCols();
LONG FP_RestrictRows();
LONG FP_Row();
LONG FP_Row2();
LONG FP_RowHeight();
LONG FP_Shadow();
LONG FP_Shadow();
LONG FP_Shadow();
LONG FP_Text();
LONG FP_Value();
LONG FP_TopRow();
LONG FP_DateMin();
LONG FP_DateMax();
LONG FP_DateFormat();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_CellType2();
LONG FP_FloatMax();
LONG FP_FloatMin();
LONG FP_PicMask();
LONG FP_PicDefText();
LONG FP_StaticText();
LONG FP_StaticText();
LONG FP_StaticText();
LONG FP_StaticText();
LONG FP_TimeMin();
LONG FP_TimeMax();
LONG FP_Time();
LONG FP_Time();
LONG FP_Time();
LONG FP_ScrollBars();
LONG FP_SelLength();
LONG FP_SelStart();
LONG FP_SelText();
LONG FP_EditModePermanent();
LONG FP_RowsFrozen();
LONG FP_ColsFrozen();
LONG FP_Autosize();
LONG FP_VisibleRows();
LONG FP_VisibleCols();
LONG FP_ScrollBarExtMode();
LONG FP_ScrollBarsHowMax();
LONG FP_ScrollBarMaxAlign();
LONG FP_ButtonText();
LONG FP_ButtonPicName();
LONG FP_ButtonPicDown();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ButtonProps();
LONG FP_ComboList();
LONG FP_Print();
LONG FP_ProcessTab();
LONG FP_LockBackColor();
LONG FP_LockForeColor();
LONG FP_UnitType();
LONG FP_EditEnterAction();
LONG FP_GrayAreaBackColor();
LONG FP_ArrowsExitEditMode();
LONG FP_MoveActiveOnFocus();
LONG FP_GrayAreaForeColor();
LONG FP_TypePictPicture();
LONG FP_TypePictCenter();
LONG FP_TypePictStretch();
LONG FP_TypePictScale();
LONG FP_RetainSelBlock();
LONG FP_AllowUserFormulas();
LONG FP_NoBeep();
LONG FP_OperationMode();
LONG FP_OffSetFromBeg();
LONG FP_EditModeReplace();
LONG FP_LoadTabFile();
LONG FP_AllowMultiBlocks();
LONG FP_ActiveCol();
LONG FP_ActiveRow();
LONG FP_SelectBlockCol();
LONG FP_SelectBlockCol2();
LONG FP_SelectBlockRow();
LONG FP_SelectBlockRow2();
LONG FP_IsBlockSelected();
LONG FP_Spread_hWnd();
LONG FP_MaxTextColWidth();
LONG FP_MaxTextCellWidth();
LONG FP_MaxTextRowHeight();
LONG FP_MaxTextCellHeight();
LONG FP_DataColCnt();
LONG FP_DataRowCnt();

LONG FP_AutoClipboard();
LONG FP_AllowMultiBlocks();
LONG FP_AllowCellOverflow();
LONG FP_AllowDragDrop();

LONG FP_ChangeMade();
LONG FP_GridLineColor();
LONG FP_VScrollSpecial();
LONG FP_VScrollSpecialType();
LONG FP_UserResizeRow();
LONG FP_UserResizeCol();
LONG FP_UserResize();
LONG FP_RowHidden();
LONG FP_ColHidden();
LONG FP_ButtonDrawMode();
LONG FP_SelectBlockOptions();
LONG FP_OperationMode();
LONG FP_SortKey1Order();
LONG FP_SortKey2Order();
LONG FP_SortKey3Order();
LONG FP_SortKey1();
LONG FP_SortKey2();
LONG FP_SortKey3();
LONG FP_SortBy();

LONG FP_TypeFloatChars();
LONG FP_TypeFloatDefCur();
LONG FP_TypeFloatDefDecimal();
LONG FP_TypeFloatDefSep();
LONG FP_CursorType();
LONG FP_CursorStyle();
LONG FP_CursorIcon();
LONG FP_BorderType();
LONG FP_BorderStyle();
LONG FP_BorderColor();
LONG FP_MultiSelIndex();
LONG FP_MultiSelCount();
LONG FP_DestCol();
LONG FP_DestRow();

LONG FP_ColPageBreak(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_RowPageBreak(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualRows(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                    WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualOverlap(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualMode(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                    WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualCurRowCount(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                           WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualCurTop(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                      WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualMaxRows(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_VirtualScrollBuffer(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                            WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeSpin(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                 WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeIntSpinWrap(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                        WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeIntSpinInc(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeTextPrefix(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeTextShadowIn(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                         WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeComboBoxEditable(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                             WPARAM wParam, LPARAM lParam,
                             LPVBSPREAD lpSpread);
LONG FP_NoBorder(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                 WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_GridSolid(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                  WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_GridShowHoriz(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                      WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_GridShowVert(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeOwnerDrawStyle(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                           WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_CheckCenter(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                    WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_CheckText(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                  WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_CheckPicture(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_CheckTextAlign(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_StartingColNumber(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                          WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_StartingRowNumber(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                          WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_ColHeaderDisplay(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                         WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_RowHeaderDisplay(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                         WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_SortKey(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_SortKeyOrder(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_Bound(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
              WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_DataFillEvent(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                      WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_DataFieldName(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                      WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeComboBox(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                      WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TypeSelMode(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                    WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_Utopia(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
               WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_Bool(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
             WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_DataConnect(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                    WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_DataSelect(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                   WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FPSS_About(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_BackColorStyle(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_Appearance(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                   WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TextTip(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_TextTipDelay(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_ScrollBarTrack(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                       WPARAM wParam, LPARAM lParam, LPVBSPREAD lpSpread);
LONG FP_ClipboardOptions(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                         WORD wParam, LONG lParam, LPVBSPREAD lpSpread);
LONG FP_SelBackColor(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WORD wParam, LONG lParam, LPVBSPREAD lpSpread);
LONG FP_SelForeColor(BOOL fSetProp, HCTL hCtl, HWND hWnd, WORD Msg,
                     WORD wParam, LONG lParam, LPVBSPREAD lpSpread);
