//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SPLASH.RC
//

#include "..\sssrc\spread\language.h"

#define IDS_UNITTYPE_NORMAL             501
#define IDS_UNITTYPE_VGA                502
#define IDS_UNITTYPE_TWIPS              503
#define IDS_HEADERDISP_BLANK            504
#define IDS_HEADERDISP_NUMBERS          505
#define IDS_HEADERDISP_LETTERS          506
#define IDS_DAUTOSIZE_OFF               507
#define IDS_DAUTOSIZE_MAXCOL            508
#define IDS_DAUTOSIZE_BESTGUESS         509
#define IDS_EDITENTER_NONE              510
#define IDS_EDITENTER_UP                511
#define IDS_EDITENTER_DOWN              512
#define IDS_EDITENTER_LEFT              513
#define IDS_EDITENTER_RIGHT             514
#define IDS_EDITENTER_NEXT              515
#define IDS_EDITENTER_PREV              516
#define IDS_EDITENTER_SAME              517
#define IDS_EDITENTER_NEXTROW           518
#define IDS_OPERATION_NORMAL            519
#define IDS_OPERATION_READONLY          520
#define IDS_OPERATION_ROWMODE           521
#define IDS_OPERATION_SINGLESEL         522
#define IDS_OPERATION_MULTISEL          523
#define IDS_OPERATION_EXTSEL            524
#define IDS_POSITION_UL                 525
#define IDS_POSITION_UC                 526
#define IDS_POSITION_UR                 527
#define IDS_POSITION_CL                 528
#define IDS_POSITION_C                  529
#define IDS_POSITION_CR                 530
#define IDS_POSITION_BL                 531
#define IDS_POSITION_BC                 532
#define IDS_POSITION_BR                 533
#define IDS_SCROLLBARS_NONE             534
#define IDS_SCROLLBARS_HORZ             535
#define IDS_SCROLLBARS_VERT             536
#define IDS_SCROLLBARS_BOTH             537
#define IDS_BACKCOLORSTYLE_OVERGRID     538
#define IDS_BACKCOLORSTYLE_UNDERGRID    539
#define IDS_BACKCOLORSTYLE_OVERHORZGRIDONLY 540
#define IDS_BACKCOLORSTYLE_OVERVERTGRIDONLY 541
#define IDS_ERR_CALENDARLOCK            5001
#define IDS_ERR_NODBENGINE              5002
#define IDS_ERR_DBENGINEHDR             5003
#define IDS_ERR_NO_QE_DLL               5004
#define IDS_ERR_DLLERROR                5005
#define IDS_ERR_ERROR                   5006
#define IDS_ERR_NOLICENSE               5007

// - Resource ID's for JAPANESE version of VBX.
#define IDSJ_UNITTYPE_NORMAL            (LANGUAGE_JPN)+501
#define IDSJ_UNITTYPE_VGA               (LANGUAGE_JPN)+502
#define IDSJ_UNITTYPE_TWIPS             (LANGUAGE_JPN)+503
#define IDSJ_HEADERDISP_BLANK           (LANGUAGE_JPN)+504
#define IDSJ_HEADERDISP_NUMBERS         (LANGUAGE_JPN)+505
#define IDSJ_HEADERDISP_LETTERS         (LANGUAGE_JPN)+506
#define IDSJ_DAUTOSIZE_OFF              (LANGUAGE_JPN)+507
#define IDSJ_DAUTOSIZE_MAXCOL           (LANGUAGE_JPN)+508
#define IDSJ_DAUTOSIZE_BESTGUESS        (LANGUAGE_JPN)+509
#define IDSJ_EDITENTER_NONE             (LANGUAGE_JPN)+510
#define IDSJ_EDITENTER_UP               (LANGUAGE_JPN)+511
#define IDSJ_EDITENTER_DOWN             (LANGUAGE_JPN)+512
#define IDSJ_EDITENTER_LEFT             (LANGUAGE_JPN)+513
#define IDSJ_EDITENTER_RIGHT            (LANGUAGE_JPN)+514
#define IDSJ_EDITENTER_NEXT             (LANGUAGE_JPN)+515
#define IDSJ_EDITENTER_PREV             (LANGUAGE_JPN)+516
#define IDSJ_EDITENTER_SAME             (LANGUAGE_JPN)+517
#define IDSJ_EDITENTER_NEXTROW          (LANGUAGE_JPN)+518
#define IDSJ_OPERATION_NORMAL           (LANGUAGE_JPN)+519
#define IDSJ_OPERATION_READONLY         (LANGUAGE_JPN)+520
#define IDSJ_OPERATION_ROWMODE          (LANGUAGE_JPN)+521
#define IDSJ_OPERATION_SINGLESEL        (LANGUAGE_JPN)+522
#define IDSJ_OPERATION_MULTISEL         (LANGUAGE_JPN)+523
#define IDSJ_OPERATION_EXTSEL           (LANGUAGE_JPN)+524
#define IDSJ_POSITION_UL                (LANGUAGE_JPN)+525
#define IDSJ_POSITION_UC                (LANGUAGE_JPN)+526
#define IDSJ_POSITION_UR                (LANGUAGE_JPN)+527
#define IDSJ_POSITION_CL                (LANGUAGE_JPN)+528
#define IDSJ_POSITION_C                 (LANGUAGE_JPN)+529
#define IDSJ_POSITION_CR                (LANGUAGE_JPN)+530
#define IDSJ_POSITION_BL                (LANGUAGE_JPN)+531
#define IDSJ_POSITION_BC                (LANGUAGE_JPN)+532
#define IDSJ_POSITION_BR                (LANGUAGE_JPN)+533
#define IDSJ_SCROLLBARS_NONE            (LANGUAGE_JPN)+534
#define IDSJ_SCROLLBARS_HORZ            (LANGUAGE_JPN)+535
#define IDSJ_SCROLLBARS_VERT            (LANGUAGE_JPN)+536
#define IDSJ_SCROLLBARS_BOTH            (LANGUAGE_JPN)+537
#define IDSJ_BACKCOLORSTYLE_OVERGRID    (LANGUAGE_JPN)+538
#define IDSJ_BACKCOLORSTYLE_UNDERGRID   (LANGUAGE_JPN)+539
#define IDSJ_BACKCOLORSTYLE_OVERHORZGRIDONLY (LANGUAGE_JPN)+540
#define IDSJ_BACKCOLORSTYLE_OVERVERTGRIDONLY (LANGUAGE_JPN)+541

#define IDSJ_ERR_CALENDARLOCK           (LANGUAGE_JPN)+5001
#define IDSJ_ERR_NODBENGINE             (LANGUAGE_JPN)+5002
#define IDSJ_ERR_DBENGINEHDR            (LANGUAGE_JPN)+5003
#define IDSJ_ERR_NO_QE_DLL              (LANGUAGE_JPN)+5004
#define IDSJ_ERR_DLLERROR               (LANGUAGE_JPN)+5005
#define IDSJ_ERR_ERROR                  (LANGUAGE_JPN)+5006
#define IDSJ_ERR_NOLICENSE              (LANGUAGE_JPN)+5007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
