//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by STRINGRC.RC
//

#include "..\sssrc\spread\language.h"

// - Resource ID's for US version of VBX.

#define IDS_JANUARY                     101
#define IDS_FEBUARY                     102
#define IDS_MARCH                       103
#define IDS_APRIL                       104
#define IDS_MAY                         105
#define IDS_JUNE                        106
#define IDS_JULY                        107
#define IDS_AUGUST                      108
#define IDS_SEPTEMBER                   109
#define IDS_OCTOBER                     110
#define IDS_NOVEMBER                    111
#define IDS_DECEMBER                    112

#define IDS_SUNDAY                      201
#define IDS_MONDAY                      202
#define IDS_TUESDAY                     203
#define IDS_WEDNESDAY                   204
#define IDS_THURSDAY                    205
#define IDS_FRIDAY                      206
#define IDS_SATURDAY                    207

#define IDS_UNITTYPE_NORMAL             501
#define IDS_UNITTYPE_VGA                502
#define IDS_UNITTYPE_TWIPS              503
#define IDS_HEADERDISP_BLANK            504
#define IDS_HEADERDISP_NUMBERS          505
#define IDS_HEADERDISP_LETTERS          506
#define IDS_DAUTOSIZE_OFF               507
#define IDS_DAUTOSIZE_MAXCOL            508
#define IDS_DAUTOSIZE_BESTGUESS         509
#define IDS_EDITENTER_NONE              510
#define IDS_EDITENTER_UP                511
#define IDS_EDITENTER_DOWN              512
#define IDS_EDITENTER_LEFT              513
#define IDS_EDITENTER_RIGHT             514
#define IDS_EDITENTER_NEXT              515
#define IDS_EDITENTER_PREV              516
#define IDS_EDITENTER_SAME              517
#define IDS_EDITENTER_NEXTROW           518
#define IDS_OPERATION_NORMAL            519
#define IDS_OPERATION_READONLY          520
#define IDS_OPERATION_ROWMODE           521
#define IDS_OPERATION_SINGLESEL         522
#define IDS_OPERATION_MULTISEL          523
#define IDS_OPERATION_EXTSEL            524
#define IDS_POSITION_UL                 525
#define IDS_POSITION_UC                 526
#define IDS_POSITION_UR                 527
#define IDS_POSITION_CL                 528
#define IDS_POSITION_C                  529
#define IDS_POSITION_CR                 530
#define IDS_POSITION_BL                 531
#define IDS_POSITION_BC                 532
#define IDS_POSITION_BR                 533
#define IDS_SCROLLBARS_NONE             534
#define IDS_SCROLLBARS_HORZ             535
#define IDS_SCROLLBARS_VERT             536
#define IDS_SCROLLBARS_BOTH             537
#define IDS_BACKCOLORSTYLE_OVERGRID     538
#define IDS_BACKCOLORSTYLE_UNDERGRID    539

#define IDS_SEPARATOR_YEAR              1001
#define IDS_SEPARATOR_MONTH             1002
#define IDS_SEPARATOR_DAY               1003
#define IDS_CALENDAR_CAPTION            1004
#define IDS_ERA_MEIJI                   1005
#define IDS_ERA_TAISHO                  1006
#define IDS_ERA_SHOWA                   1007
#define IDS_ERA_HEISEI                  1008
#define IDS_ABOUTTEXT                   1009
#define IDS_SEPARATOR_HOUR              1010
#define IDS_SEPARATOR_MINUTE            1011
#define IDS_SEPARATOR_SECOND            1012
#define IDS_TIME_AM                     1013
#define IDS_TIME_PM                     1014

#define IDS_ERR_CALENDARLOCK            5001
#define IDS_ERR_NODBENGINE              5002
#define IDS_ERR_DBENGINEHDR             5003
#define IDS_ERR_NO_QE_DLL               5004
#define IDS_ERR_DLLERROR                5005
#define IDS_ERR_ERROR                   5006
#define IDS_ERR_NOLICENSE               5007

#define IDS_SHEET_STRING                1050


// - Resource ID's for JAPANESE version of VBX.
#define IDSJ_JANUARY                    (LANGUAGE_JPN)+101
#define IDSJ_FEBUARY                    (LANGUAGE_JPN)+102
#define IDSJ_MARCH                      (LANGUAGE_JPN)+103
#define IDSJ_APRIL                      (LANGUAGE_JPN)+104
#define IDSJ_MAY                        (LANGUAGE_JPN)+105
#define IDSJ_JUNE                       (LANGUAGE_JPN)+106
#define IDSJ_JULY                       (LANGUAGE_JPN)+107
#define IDSJ_AUGUST                     (LANGUAGE_JPN)+108
#define IDSJ_SEPTEMBER                  (LANGUAGE_JPN)+109
#define IDSJ_OCTOBER                    (LANGUAGE_JPN)+110
#define IDSJ_NOVEMBER                   (LANGUAGE_JPN)+111
#define IDSJ_DECEMBER                   (LANGUAGE_JPN)+112

#define IDSJ_SUNDAY                     (LANGUAGE_JPN)+201
#define IDSJ_MONDAY                     (LANGUAGE_JPN)+202
#define IDSJ_TUESDAY                    (LANGUAGE_JPN)+203
#define IDSJ_WEDNESDAY                  (LANGUAGE_JPN)+204
#define IDSJ_THURSDAY                   (LANGUAGE_JPN)+205
#define IDSJ_FRIDAY                     (LANGUAGE_JPN)+206
#define IDSJ_SATURDAY                   (LANGUAGE_JPN)+207

#define IDSJ_UNITTYPE_NORMAL            (LANGUAGE_JPN)+501
#define IDSJ_UNITTYPE_VGA               (LANGUAGE_JPN)+502
#define IDSJ_UNITTYPE_TWIPS             (LANGUAGE_JPN)+503
#define IDSJ_HEADERDISP_BLANK           (LANGUAGE_JPN)+504
#define IDSJ_HEADERDISP_NUMBERS         (LANGUAGE_JPN)+505
#define IDSJ_HEADERDISP_LETTERS         (LANGUAGE_JPN)+506
#define IDSJ_DAUTOSIZE_OFF              (LANGUAGE_JPN)+507
#define IDSJ_DAUTOSIZE_MAXCOL           (LANGUAGE_JPN)+508
#define IDSJ_DAUTOSIZE_BESTGUESS        (LANGUAGE_JPN)+509
#define IDSJ_EDITENTER_NONE             (LANGUAGE_JPN)+510
#define IDSJ_EDITENTER_UP               (LANGUAGE_JPN)+511
#define IDSJ_EDITENTER_DOWN             (LANGUAGE_JPN)+512
#define IDSJ_EDITENTER_LEFT             (LANGUAGE_JPN)+513
#define IDSJ_EDITENTER_RIGHT            (LANGUAGE_JPN)+514
#define IDSJ_EDITENTER_NEXT             (LANGUAGE_JPN)+515
#define IDSJ_EDITENTER_PREV             (LANGUAGE_JPN)+516
#define IDSJ_EDITENTER_SAME             (LANGUAGE_JPN)+517
#define IDSJ_EDITENTER_NEXTROW          (LANGUAGE_JPN)+518
#define IDSJ_OPERATION_NORMAL           (LANGUAGE_JPN)+519
#define IDSJ_OPERATION_READONLY         (LANGUAGE_JPN)+520
#define IDSJ_OPERATION_ROWMODE          (LANGUAGE_JPN)+521
#define IDSJ_OPERATION_SINGLESEL        (LANGUAGE_JPN)+522
#define IDSJ_OPERATION_MULTISEL         (LANGUAGE_JPN)+523
#define IDSJ_OPERATION_EXTSEL           (LANGUAGE_JPN)+524
#define IDSJ_POSITION_UL                (LANGUAGE_JPN)+525
#define IDSJ_POSITION_UC                (LANGUAGE_JPN)+526
#define IDSJ_POSITION_UR                (LANGUAGE_JPN)+527
#define IDSJ_POSITION_CL                (LANGUAGE_JPN)+528
#define IDSJ_POSITION_C                 (LANGUAGE_JPN)+529
#define IDSJ_POSITION_CR                (LANGUAGE_JPN)+530
#define IDSJ_POSITION_BL                (LANGUAGE_JPN)+531
#define IDSJ_POSITION_BC                (LANGUAGE_JPN)+532
#define IDSJ_POSITION_BR                (LANGUAGE_JPN)+533
#define IDSJ_SCROLLBARS_NONE            (LANGUAGE_JPN)+534
#define IDSJ_SCROLLBARS_HORZ            (LANGUAGE_JPN)+535
#define IDSJ_SCROLLBARS_VERT            (LANGUAGE_JPN)+536
#define IDSJ_SCROLLBARS_BOTH            (LANGUAGE_JPN)+537
#define IDSJ_BACKCOLORSTYLE_OVERGRID    (LANGUAGE_JPN)+538
#define IDSJ_BACKCOLORSTYLE_UNDERGRID   (LANGUAGE_JPN)+539

#define IDSJ_SEPARATOR_YEAR             (LANGUAGE_JPN)+1001
#define IDSJ_SEPARATOR_MONTH            (LANGUAGE_JPN)+1002
#define IDSJ_SEPARATOR_DAY              (LANGUAGE_JPN)+1003
#define IDSJ_CALENDAR_CAPTION           (LANGUAGE_JPN)+1004
#define IDSJ_ERA_MEIJI                  (LANGUAGE_JPN)+1005
#define IDSJ_ERA_TAISHO                 (LANGUAGE_JPN)+1006
#define IDSJ_ERA_SHOWA                  (LANGUAGE_JPN)+1007
#define IDSJ_ERA_HEISEI                 (LANGUAGE_JPN)+1008
#define IDSJ_ABOUTTEXT                  (LANGUAGE_JPN)+1009
#define IDSJ_SEPARATOR_HOUR             (LANGUAGE_JPN)+1010
#define IDSJ_SEPARATOR_MINUTE           (LANGUAGE_JPN)+1011
#define IDSJ_SEPARATOR_SECOND           (LANGUAGE_JPN)+1012
#define IDSJ_TIME_AM                    (LANGUAGE_JPN)+1013
#define IDSJ_TIME_PM                    (LANGUAGE_JPN)+1014

#define IDSJ_ERR_CALENDARLOCK           (LANGUAGE_JPN)+5001
#define IDSJ_ERR_NODBENGINE             (LANGUAGE_JPN)+5002
#define IDSJ_ERR_DBENGINEHDR            (LANGUAGE_JPN)+5003
#define IDSJ_ERR_NO_QE_DLL              (LANGUAGE_JPN)+5004
#define IDSJ_ERR_DLLERROR               (LANGUAGE_JPN)+5005
#define IDSJ_ERR_ERROR                  (LANGUAGE_JPN)+5006
#define IDSJ_ERR_NOLICENSE              (LANGUAGE_JPN)+5007
