//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xl.rc
//
#define IDS_LOGS_OPEN                   3100
#define IDS_LOGS_CLOSE                  3101
#define IDS_LOGS_REGISTRYPROPS          3102
#define IDS_LOGS_LOADFILE               3120
#define IDS_LOGS_INTEGERCELLTYPE        3121
#define IDS_LOGS_INVALIDTOKEN           3122
#define IDS_LOGS_FORMATNOTSUPPORTED     3123
#define IDS_LOGS_DATEFORMATNOTSUPPORTED 3124
#define IDS_LOGS_FORMAT0IGNORED         3125
#define IDS_LOGS_FORMAT0FORCED          3126
#define IDS_LOGS_IGNOREDTOKEN           3127
#define IDS_LOGS_FORMATFRACTION         3128
#define IDS_LOGS_FORMATPERCENT          3129
#define IDS_LOGS_FORMATSCIENTIFIC       3130
#define IDS_LOGS_PMTFUNCTIONLOAD        3131
#define IDS_LOGS_CELLOBJECTSNOTSUPPORTED 3132
#define IDS_LOGS_FORMPTGNOTSUPPORTED    3133
#define IDS_LOGS_FUNCFORMCELLTYPE       3134
#define IDS_LOGS_FUNCNOTSUPPORTED       3135
#define IDS_LOGS_FORMERROR              3136
#define IDS_LOGS_FLOATOUTOFBOUNDS       3137
#define IDS_LOGS_CURRENCYMULTIPLECHARS  3138
#define IDS_LOGS_CURRENCYNOTFIRST       3139
#define IDS_LOGS_RICHTEXTNOTSUPPORTED   3140
#define IDS_LOGS_IFFUNCTIONLOAD         3141
#define IDS_LOGS_TRUNCFUNCTIONLOAD      3142
#define IDS_LOGS_SAVEFILE               3160
#define IDS_LOGS_DATEOUTOFRANGE         3161
#define IDS_LOGS_OBJCELLTYPE            3162
#define IDS_LOGS_PMTFUNCTIONSAVE        3163
#define IDS_LOGS_PICTOKENNOTSUPPORTED   3164
#define IDS_LOGS_TOOMANYCOLS            3165
#define IDS_LOGS_TOOMANYROWS            3166
#define IDS_LOGS_CUSTFUNCNOTSUPPORTED   3167
#define IDS_LOGS_XROOTFUNCTIONSAVE      3168
#define IDS_LOGS_IFFUNCTIONSAVE         3169
#define IDS_LOGS_FP                     3180
#define IDS_LOGS_CLOSE_IMPWB            3181
#define IDS_LOGS_CLOSE_IMPSHEET         3182
#define IDS_LOGS_CLOSE_EXPORT           3183
#define IDS_LOGS_EXPORTCHECKBOX         3184
#define IDS_LOGS_EXPORTBUTTON           3185
#define IDS_LOGS_EXPORTCOMBOBOX         3186
#define IDS_LOGS_HEADERSTUFF            3187
#define IDS_LOGS_OPEN_EXPORT            3188
#define IDS_LOGS_LOADSHEET              3189
#define IDS_LOGS_OPEN_IMPWB             3190
#define IDS_LOGS_OPEN_IMPSHEET          3191
#define IDS_LOGS_MULTIPLEFORMATS        3200
#define IDS_LOGS_CUSTHEADERNOTSUPPORTED 3201
#define IDS_LOGS_URLFUNCTIONNOTIFY      3202
#define IDS_LOGS_FEB291900              3203
#define IDS_LOGS_EXPORTSTATICTEXT       3204
#define IDS_LOGS_PASSWORD               3205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
